"""add ascii table

Revision ID: 542e7c09adba
Revises: 380f7ceaa64e
Create Date: 2023-11-02 07:12:07.199265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542e7c09adba'
down_revision = '380f7ceaa64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascii_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=False),
    sa.Column('colour', sa.Boolean(), nullable=False),
    sa.Column('highlights', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ascii_img')
    # ### end Alembic commands ###
