"""update img table

Revision ID: 8778dbc86e4c
Revises: 542e7c09adba
Create Date: 2023-11-06 15:17:55.371397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8778dbc86e4c'
down_revision = '542e7c09adba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascii_img', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascii_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
