"""update user db

Revision ID: d22533c83a2f
Revises: df22724b0c28
Create Date: 2023-11-11 09:55:50.525526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd22533c83a2f'
down_revision = 'df22724b0c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascii_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=2000), nullable=False))
        batch_op.add_column(sa.Column('ascci', sa.String(length=2000), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascii_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.VARCHAR(length=2000), nullable=False))
        batch_op.drop_column('ascci')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
